version: '3.8'

services:
  jukebox:
    build: .
    container_name: pi_jukebox
    restart: unless-stopped
    ports:
      - "3001:3000"
    volumes:
      # Mount your music collection (read-only)
      - ./music:/app/music:ro
      # Persistent data directories
      - ./database:/app/database
      - ./uploads:/app/uploads
      # Optional: custom configuration
      - ./.env:/app/.env:ro
    environment:
      - NODE_ENV=production
      - JWT_SECRET=${JWT_SECRET:-your-super-secret-jwt-key-change-this-to-something-secure}
      - PORT=3000
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    # Resource limits (adjust based on your Pi's capabilities)
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M
    # Logging configuration
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"